apiVersion: v1
kind: Pod
metadata:
  name: python-app-pod
  labels:
    app: python-app
spec:
  containers:
    - name: python-container
      image: python-k8s-app:latest
      imagePullPolicy: Never  
      ports:
        - containerPort: 8000
