apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8000       # Port exposed within the cluster
      targetPort: 8000 # Port on the pod container
  type: ClusterIP   # Default service type, accessible only within the cluster
