apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 8000        # Port inside the cluster (service port)
      targetPort: 8000  # Port your container listens on
      nodePort: 30036   # Port on the worker node (between 30000–32767)
